packages:
  - packages/*

overrides:
  '@langchain/core': ^1.1.44

patchedDependencies:
  conventional-changelog-conventionalcommits: patches/conventional-changelog-conventionalcommits.patch
  n8n-core: patches/n8n-core.patch
  n8n: patches/n8n.patch

# Sheet-JS xlsx package can only be downloaded from their own CDN 
blockExoticSubdeps: false

verifyDepsBeforeRun: error

ignoredBuiltDependencies:
  - oxc-resolver

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@sentry/node-cpu-profiler': true
  '@sentry/node-native-stacktrace': true
  agent-browser: true
  canvas: true
  cpu-features: true
  eslint-plugin-n8n-nodes-base: true
  isolated-vm: true
  msgpackr-extract: true
  oracledb: true
  protobufjs: true
  sqlite3: true
  ssh2: true
  unrs-resolver: true
