name: Setup Turborepo
description: Prepare and install everything for Turborepo

inputs:
  node-registry-url:
    description: The Node.js registry URL to use
    required: false

  node-version-file:
    description: The file to read the Node.js version from
    required: false

  turbo-s3-endpoint:
    description: S3 endpoint for Turbo cache server
    required: false

  turbo-s3-region:
    description: S3 region for Turbo cache server
    required: false

  turbo-s3-bucket:
    description: S3 bucket name for Turbo cache server
    required: false

  turbo-s3-access-key:
    description: S3 access key for Turbo cache server
    required: false

  turbo-s3-secret-key:
    description: S3 secret key for Turbo cache server
    required: false

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm
        registry-url: ${{ inputs.node-registry-url }}

    - name: Setup Turbo cache server
      if: ${{ inputs.turbo-s3-bucket != '' }}
      uses: brunojppb/turbo-cache-server@2.0.9
      env:
        S3_ENDPOINT: ${{ inputs.turbo-s3-endpoint }}
        S3_REGION: ${{ inputs.turbo-s3-region }}
        S3_BUCKET_NAME: ${{ inputs.turbo-s3-bucket }}
        S3_ACCESS_KEY: ${{ inputs.turbo-s3-access-key }}
        S3_SECRET_KEY: ${{ inputs.turbo-s3-secret-key }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
