name: Install canvas build dependencies

description: Install native packages required to compile node-canvas

runs:
  using: composite

  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgif-dev \
          libjpeg-dev \
          libpango1.0-dev \
          librsvg2-dev;
