name: dependabot Pull Request Enhancer

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  cancel-code-check:
    name: Cancel Code Check
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && (contains(github.event.pull_request.title, 'Bump nx') || contains(github.event.pull_request.title, 'Bump n8n'))
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cancel Code Check
        run: |
          set -e

          run_id=$(gh run list --branch ${{ github.event.pull_request.head.ref }} --workflow "Code Check" --json status,databaseId --jq 'first(.[] | select(.status == "queued" or .status == "in_progress" or .status == "requested" or .status == "waiting" or .status == "completed") | .databaseId)')

          if [ -n "$run_id" ]; then
            gh run cancel ${run_id}
          else
            echo "No matching run found to cancel."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-nx-dependency-update-workflow:
    name: Trigger nx Dependency Update Workflow
    uses: ./.github/workflows/nx-dependency-update.yaml
    with:
      pull_request_ref: ${{ github.event.pull_request.head.ref }}
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'Bump nx')
    permissions:
      contents: write

  trigger-n8n-dependency-update-workflow:
    name: Trigger n8n Dependency update Workflow
    uses: ./.github/workflows/n8n-dependency-update.yaml
    with:
      pull_request_ref: ${{ github.event.pull_request.head.ref }}
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'Bump n8n')
    permissions:
      contents: write

  trigger-code-check-workflow:
    name: Trigger Code Check Workflow
    uses: ./.github/workflows/code-check.yaml
    with:
      pull_request_ref: ${{ github.event.pull_request.head.ref }}
    if: always() && (needs.trigger-nx-dependency-update-workflow.result == 'success' || needs.trigger-n8n-dependency-update-workflow.result == 'success')
    needs:
      - trigger-nx-dependency-update-workflow
      - trigger-n8n-dependency-update-workflow
