name: n8n Dependency Update

on:
  workflow_dispatch:
    inputs:
      pull_request_ref:
        required: true
        type: string
  workflow_call:
    inputs:
      pull_request_ref:
        required: true
        type: string

jobs:
  update-node-version:
    name: Update Node.js Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.pull_request_ref }}

      - name: Install canvas deps
        uses: ./.github/actions/install-canvas-deps

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install

      - name: Retrieve target versions
        id: target-versions
        run: |
          set -e
          n8n_version=$(pnpm list n8n --filter @skriptfabrik/n8n-nodes --json | jq --raw-output --exit-status '.[0].devDependencies.n8n.version')
          node_version=$(docker run --rm --entrypoint node n8nio/n8n:${n8n_version} --version | sed 's/^v//')
          node_types_version=$(pnpm show @types/node versions --json | jq --raw-output --arg node_version "${node_version}" 'map(select(. <= $node_version)) | map(split(".") | map(tonumber)) | max_by(.) | join(".")')
          echo "node_version=${node_version}" >> "$GITHUB_OUTPUT"
          echo "node_types_version=${node_types_version}" >> "$GITHUB_OUTPUT"

      - name: Update node version in package.json
        run: |
          yq --inplace --exit-status '.engines.node = "${{steps.target-versions.outputs.node_version}}"' package.json
          yq --inplace --exit-status '.devEngines.runtime.version = "${{steps.target-versions.outputs.node_version}}"' package.json

      - name: Commit node version update in package.json
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: bump node version in package.json to ${{steps.target-versions.outputs.node_version}}'
          commit_options: '--signoff'

      - name: Update node version in devcontainer.json
        run: yq --inplace --exit-status '.features."ghcr.io/devcontainers/features/node:1".version = "${{steps.target-versions.outputs.node_version}}"' .devcontainer/devcontainer.json

      - name: Commit node version update in devcontainer.json
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: bump node version in devcontainer to ${{steps.target-versions.outputs.node_version}}'
          commit_options: '--signoff'

      - name: Update @types/node
        run: |
          pnpm add @types/node@~${{ steps.target-versions.outputs.node_types_version }} \
            --ignore-workspace-root-check \
            --save-dev

      - name: Commit @types/node update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: bump @types/node version to ${{ steps.target-versions.outputs.node_types_version }}'
          commit_options: '--signoff'

  update-n8n-dependencies-in-root:
    name: Update n8n Dependencies in Root
    needs: update-node-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.pull_request_ref }}

      - name: Install canvas deps
        uses: ./.github/actions/install-canvas-deps

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install

      - name: Retrieve target versions
        id: target-versions
        run: |
          set -e
          n8n_nodes_base_version=$(pnpm list n8n-nodes-base --json --depth 1 | jq --raw-output --exit-status '.[0].devDependencies.n8n.dependencies."n8n-nodes-base".version')
          n8n_workflow_version=$(pnpm list n8n-workflow --json --depth 1 | jq --raw-output --exit-status '.[0].devDependencies.n8n.dependencies."n8n-workflow".version')
          echo "n8n_nodes_base_version=${n8n_nodes_base_version}" >> "$GITHUB_OUTPUT"
          echo "n8n_workflow_version=${n8n_workflow_version}" >> "$GITHUB_OUTPUT"

      - name: Update n8n-nodes-base
        run: |
          pnpm update n8n-nodes-base@${{ steps.target-versions.outputs.n8n_nodes_base_version }} \
            --no-save

      - name: Commit n8n-nodes-base update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: bump n8n-nodes-base version to ${{ steps.target-versions.outputs.n8n_nodes_base_version }}'
          commit_options: '--signoff'

      - name: Update n8n-workflow
        run: |
          pnpm update n8n-workflow@${{ steps.target-versions.outputs.n8n_workflow_version }} \
            --no-save

      - name: Commit n8n-workflow update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: bump n8n-workflow version to ${{ steps.target-versions.outputs.n8n_workflow_version }}'
          commit_options: '--signoff'

  update-n8n-versions-in-packages:
    name: Update n8n Dependencies in Packages
    needs: update-n8n-dependencies-in-root
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - name: '@skriptfabrik/n8n-nodes-barcode'
            workspace: barcode
          - name: '@skriptfabrik/n8n-nodes-channable'
            workspace: channable
          - name: '@skriptfabrik/n8n-nodes-clockify-enhanced'
            workspace: clockify-enhanced
          - name: '@skriptfabrik/n8n-nodes-cronhooks'
            workspace: cronhooks
          - name: '@skriptfabrik/n8n-nodes-fulfillmenttools'
            workspace: fulfillmenttools
          - name: '@skriptfabrik/n8n-nodes-google-enhanced'
            workspace: google-enhanced
          - name: '@skriptfabrik/n8n-nodes-kaufland-marketplace'
            workspace: kaufland-marketplace
          - name: '@skriptfabrik/n8n-nodes-moco'
            workspace: moco
          - name: '@skriptfabrik/n8n-nodes-otto-market'
            workspace: otto-market
          - name: '@skriptfabrik/n8n-nodes-sentry-io-enhanced'
            workspace: sentry-io-enhanced
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.pull_request_ref }}

      - name: Install canvas deps
        uses: ./.github/actions/install-canvas-deps

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install

      - name: Retrieve target versions
        id: target-versions
        run: |
          set -e
          n8n_nodes_base_version=$(pnpm list n8n-nodes-base --json --depth 1 | jq --raw-output --exit-status '.[0].devDependencies.n8n.dependencies."n8n-nodes-base".version')
          n8n_workflow_version=$(pnpm list n8n-workflow --json --depth 1 | jq --raw-output --exit-status '.[0].devDependencies.n8n.dependencies."n8n-workflow".version')
          echo "n8n_nodes_base_version=${n8n_nodes_base_version}" >> "$GITHUB_OUTPUT"
          echo "n8n_workflow_version=${n8n_workflow_version}" >> "$GITHUB_OUTPUT"

      - name: Update n8n-nodes-base version
        run: |
          pnpm update n8n-nodes-base@${{ steps.target-versions.outputs.n8n_nodes_base_version }} \
            --filter ${{ matrix.package.name }} \
            --no-save

      - name: Commit n8n-nodes-base version update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'fix(${{matrix.package.workspace}}): bump n8n-nodes-base version to ${{ steps.target-versions.outputs.n8n_nodes_base_version }}'
          commit_options: '--signoff'

      - name: Update n8n-workflow version
        run: |
          pnpm update n8n-workflow@${{ steps.target-versions.outputs.n8n_workflow_version }} \
            --filter ${{ matrix.package.name }} \
            --no-save

      - name: Commit n8n-workflow version update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'fix(${{matrix.package.workspace}}): bump n8n-workflow version to ${{ steps.target-versions.outputs.n8n_workflow_version }}'
          commit_options: '--signoff'
